# Generated by Django 5.2.17 on 2026-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                ("email", models.EmailField(max_length=320, verbose_name="Email")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "Общий вопрос"),
                            ("support", "Проблема с сервисом"),
                            ("billing", "Оплата и подписка"),
                            ("partnership", "Сотрудничество"),
                            ("legal", "Юридический вопрос"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Тема",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Отпечаток адреса"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Язык обращения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получено"),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["is_processed", "-created_at"],
                        name="contacts_co_is_proc_dbf099_idx",
                    )
                ],
            },
        ),
    ]
