# Generated by Django 5.2.17 on 2026-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("terms", "Пользовательское соглашение"),
                            ("privacy", "Политика конфиденциальности"),
                            ("consent", "Согласие на обработку персональных данных"),
                            ("cookies", "Политика в отношении cookie"),
                            ("offer", "Публичная оферта"),
                            ("refund", "Политика возврата средств"),
                            ("requisites", "Реквизиты"),
                            ("aup", "Acceptable Use Policy"),
                            ("dmca", "DMCA / Copyright Policy"),
                        ],
                        max_length=32,
                        verbose_name="Идентификатор",
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[("RU", "Россия"), ("US", "США")],
                        default="RU",
                        max_length=2,
                        verbose_name="Юрисдикция",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("en", "English")],
                        default="ru",
                        max_length=5,
                        verbose_name="Язык",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Одна строка для списка документов.",
                        max_length=500,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown: ## заголовки, списки, таблицы, **выделение**.",
                        verbose_name="Текст",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Версия"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Действует с")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=False, verbose_name="Показывать в подвале"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Порядок"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Юридический документ",
                "verbose_name_plural": "Юридические документы",
                "ordering": ("order", "title"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "jurisdiction", "language"),
                        name="uq_legal_document_slug_jurisdiction_language",
                    )
                ],
            },
        ),
    ]
