# Generated by Django 5.2.17 on 2026-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_open",
                    models.BooleanField(
                        default=True,
                        help_text="Выключите, чтобы закрыть приём новых пользователей. Страница регистрации покажет сообщение ниже, кнопки в шапке скроются.",
                        verbose_name="Регистрация открыта",
                    ),
                ),
                (
                    "registration_closed_title",
                    models.CharField(
                        default="Регистрация временно закрыта",
                        max_length=200,
                        verbose_name="Заголовок при закрытой регистрации",
                    ),
                ),
                (
                    "registration_closed_message",
                    models.TextField(
                        default="Мы приостановили приём новых участников, чтобы спокойно довести сервис до ума. Напишите нам — сообщим, когда снова откроем.",
                        verbose_name="Текст при закрытой регистрации",
                    ),
                ),
                (
                    "legal_jurisdiction",
                    models.CharField(
                        choices=[("RU", "Россия"), ("US", "США")],
                        default="RU",
                        help_text="Определяет, какой набор юридических документов показывать. Смена перестраивает раздел «Документы» целиком.",
                        max_length=2,
                        verbose_name="Юрисдикция документов",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="hello@mywayis.com",
                        max_length=254,
                        verbose_name="Email поддержки",
                    ),
                ),
                (
                    "contact_telegram",
                    models.CharField(
                        blank=True,
                        default="@mywayis",
                        max_length=100,
                        verbose_name="Telegram",
                    ),
                ),
                (
                    "support_hours",
                    models.CharField(
                        blank=True,
                        default="Отвечаем по будням с 10:00 до 19:00 МСК",
                        max_length=200,
                        verbose_name="Время ответа",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="ИП Чернов Олег",
                        max_length=255,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "company_inn",
                    models.CharField(blank=True, max_length=20, verbose_name="ИНН"),
                ),
                (
                    "company_ogrn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ОГРНИП / ОГРН"
                    ),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
                ),
                (
                    "analytics_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Пока выключено, счётчик не подключается и cookie не ставятся.",
                        verbose_name="Аналитика включена",
                    ),
                ),
                (
                    "metrika_id",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="ID Яндекс.Метрики"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
